function [fitresult, gof] = createFit_sin2(t, Qnm)
%CREATEFIT(T,QNM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: Qnm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Oct-2015 16:55:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, Qnm );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [1.41176861623033 0.000186676313685651 2.28908818058534 0.697762382544703 0.000169705739714228 -1.55334860552531];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'curve fit sin2' );
h = plot( fitresult, xData, yData );
legend( h, 'displacement vs. time', 'curve fit sin2', 'Location', 'NorthEast' );
% Label axes
xlabel( 'time (us)' );
ylabel( 'displacement (nm)' );
grid on


