function [ft,gofR2,figure_handle]= createFit_Sin_N(t, w,N,show_figure_number)
%CREATEFIT(T,W)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: w
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Jun-2016 13:13:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, w );

% Set up fittype and options.
% ft = fittype( 'sin8' );
ft = fittype( ['sin' num2str(N)  ]);
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [3634.80667402439 0.00641683511647353 2.73613412786346 1288.57669412692 0.0128336702329471 -2.09051045858325 190.980433949985 0.0256673404658941 -2.22455624311954 62.5325969264073 0.0385010106988412 -2.23251712788605 28.9018385386488 0.0513346809317883 -2.15798696712113 15.4015842745363 0.0641683511647353 -2.04422505309493 11.0944073489173 0.0770020213976824 -1.97287196407396 7.79492362456578 0.0898356916306295 -1.7880491511438];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[ft, gof] = fit( xData, yData, ft, opts );

gofR2=gof.rsquare;

figure_handle=0;
if nargin>=4
% Plot fit with data.
figure_handle=figure(show_figure_number);
h=plot( ft, xData, yData,'*')
% set(h,'MarkerSize',2);
% legend( h, 'y vs. x')
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on
end